require-stack-version: ">= 1.6"

resolver: nightly-2020-12-14

packages:
- .

extra-deps:
- git: https://github.com/facundominguez/liquidhaskell.git
  commit: 7b1729c966a129562f3e698ae8e38d044970e58c
  subdirs:
  - .
  - liquid-base
  - liquid-containers
  - liquid-ghc-prim
  - liquid-prelude
- git: https://github.com/facundominguez/liquid-fixpoint.git
  commit: bbe361dd79608cb2de1488e677cd839751884ac1
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
