require-stack-version: ">= 1.6"

resolver: nightly-2020-12-14

packages:
- .

extra-deps:
- git: https://github.com/ucsd-progsys/liquidhaskell.git
  commit: d9155afac5e4c477c1555f855cf26af4ae018006
  subdirs:
  - .
  - liquid-base
  - liquid-containers
  - liquid-ghc-prim
  - liquid-prelude
- git: https://github.com/ucsd-progsys/liquid-fixpoint.git
  commit: 707c573fb1aabd8be0ba892df20ffc5f5f043b20
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
